alter table EVENTS_
  add foreign key (customerid)
  references CUSTOMERS (customerid);
  
CREATE TABLE CustomersToClient
(
  --relid NUMBER(5),
  ClientId NUMERIC(5) NOT NULL,
  CUSTOMERID NUMERIC(5) NOT NULL,
  PRIMARY KEY (CUSTOMERID),
  FOREIGN KEY (ClientId) REFERENCES Client(ClientId),
 FOREIGN KEY (CUSTOMERID) REFERENCES CUSTOMERS(CUSTOMERID)
 --CONSTRAINT UNIQ_CUSTOMERID UNIQUE (CUSTOMERID)
  
); 
drop table CustomersToClient;

ALTER TABLE CustomersToClient
    ADD CONSTRAINT PK_CustomersToClient
    FOREIGN KEY (CUSTOMERID) REFERENCES CUSTOMERS(CUSTOMERID);
    
ALTER TABLE CustomersToClient ADD CUSTOMERID INT NOT NULL FOREIGN KEY REFERENCES CUSTOMERS(CUSTOMERID);
